### ISSUE TITLE
Add sancus?

### ISSUE THREAD

**Issue by Suchun-sv** [Oceanusity/awesome-gnns-on-large-scale-graphs#2]
SANCUS: Staleness-Aware Communication-Avoiding Full-Graph Decentralized Training in Large-Scale Graph Neural Networks, VLDB 2022 best regular reserarch paper

**Comment by Oceanusity** [comment]
Sure, feel free to add this paper to the repository.

**Comment by Suchun-sv** [comment]
Ok, Thanks
